### ISSUE TITLE
How to install it with Q2A?

### ISSUE THREAD

**Issue by Mariushrek** [neayi/q2a-rest-api#1]
Hello, 

Can you tell me how to install it with q2a? 
Is there a need to move all files under qa-plugins or it is separated service working near q2a?

Thanks,
Mariusz

**Comment by bertrandgorge** [comment]
Hello, yes, it's just a plugin - you can copy it in qa-plugins. Now please consider that this is not maintained. On our side we moved away from Q2A and are now using Discourse which is much more complete and better maintained...
